/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicAlertsRouteImport } from './routes/api/public/alerts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAlertsRoute = ApiPublicAlertsRouteImport.update({
  id: '/api/public/alerts',
  path: '/api/public/alerts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/alerts': typeof ApiPublicAlertsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/alerts': typeof ApiPublicAlertsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/alerts': typeof ApiPublicAlertsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/alerts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/alerts'
  id: '__root__' | '/' | '/api/public/alerts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicAlertsRoute: typeof ApiPublicAlertsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/alerts': {
      id: '/api/public/alerts'
      path: '/api/public/alerts'
      fullPath: '/api/public/alerts'
      preLoaderRoute: typeof ApiPublicAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicAlertsRoute: ApiPublicAlertsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
